# Tablas RawBased vs FeatureBased k=6

### Inputs files: 

#### RawBased_2009to2013.csv
#### Scores1_FeatureBasedK6.csv

##### -------------------------------------------------------------------------

In [30]:
import glob
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tsfeature as tsf
import entropy as ent

my_path = os.path.abspath('')
my_path = my_path.split('\\')
my_path_py = "\\".join(my_path[:-1])

In [31]:
RB = pd.read_csv(my_path_py+'\\1_RawBased\\RawBased_2009to2013.csv', sep=',')
F6 = pd.read_csv('Scores1_FeatureBasedK6.csv', sep=',')
RB.columns

Index(['METRICA', 'SIL - HAC', 'SIL - KM', 'SIL - DB', 'CHZ - HAC', 'CHZ - KM',
       'CHZ - DB', 'DUNN - HAC', 'DUNN - KM', 'DUNN - DB', 'DAVID - HAC',
       'DAVID - KM', 'DAVID - DB'],
      dtype='object')

In [32]:
compara = pd.DataFrame()
compara['Metrica'] = RB['METRICA']
compara['HAC RB'] = RB['SIL - HAC']
compara['HAC FB'] = F6['SIL - HAC'] 
compara['KM RB'] = RB['SIL - KM']
compara['KM FB'] = F6['SIL - KM'] 
compara['DBSCAN RB'] = RB['SIL - DB']
compara['DBSCAN FB'] = F6['SIL - DB'] 

compara

,Metrica,HAC RB,HAC FB,KM RB,KM FB,DBSCAN RB,DBSCAN FB
0,Euclidean Distance,0.667898,0.836977,0.676738,0.863019,0.694370,0.381371
1,Pearson Correlation,0.314454,0.614693,0.356793,0.646519,0.006825,0.320268
2,Spearman Correlation,0.496461,0.571987,0.514096,0.601930,0.363924,0.592432
3,Dynamic Time Warping,0.525277,0.827022,0.554136,0.861052,-0.351316,0.517592

In [33]:
compara2 = pd.DataFrame()
compara2['Metrica'] = RB['METRICA']
compara2['HAC RB'] = RB['CHZ - HAC']
compara2['HAC FB'] = F6['CHZ - HAC'] 
compara2['KM RB'] = RB['CHZ - KM']
compara2['KM FB'] = F6['CHZ - KM'] 
compara2['DBSCAN RB'] = RB['CHZ - DB']
compara2['DBSCAN FB'] = F6['CHZ - DB'] 

compara2

,Metrica,HAC RB,HAC FB,KM RB,KM FB,DBSCAN RB,DBSCAN FB
0,Euclidean Distance,1013.780870,2742.276633,1020.159559,3238.982031,184.766121,14.568195
1,Pearson Correlation,145.381454,1807.267371,167.310835,2178.141311,10.086778,426.200814
2,Spearman Correlation,239.488601,386.430859,269.004503,396.536422,54.407344,158.976210
3,Dynamic Time Warping,788.946945,2699.310719,832.699887,3164.737066,2.904499,31.070024

In [21]:
compara = pd.DataFrame()
compara['Metrica'] = RB['METRICA']
compara['HAC RB'] = RB['DAVID - HAC']
compara['HAC FB'] = F6['DAVID - HAC'] 
compara['KM RB'] = RB['DAVID - KM']
compara['KM FB'] = F6['DAVID - KM'] 
compara['DBSCAN RB'] = RB['DAVID - DB']
compara['DBSCAN FB'] = F6['DAVID - DB'] 

compara

,Metrica,HAC RB,HAC FB,KM RB,KM FB,DBSCAN RB,DBSCAN FB
0,Euclidean Distance,0.616830,0.395113,0.609003,0.331150,0.794305,1.129731
1,Pearson Correlation,1.066421,0.456257,0.977479,0.459062,0.903104,0.569509
2,Spearman Correlation,0.634745,0.715892,0.628516,0.694827,0.630810,1.098502
3,Dynamic Time Warping,0.658580,0.348792,0.671425,0.329847,1.370144,1.213330