# Tablas RawBased vs FeatureBased k=6

### Inputs files: 

#### RawBased_2009to2013.csv
#### Scores1_FeatureBasedK6.csv

##### -------------------------------------------------------------------------

In [1]:
import glob
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tsfeature as tsf
import entropy as ent

my_path = os.path.abspath('')
my_path = my_path.split('\\')
my_path_py = "\\".join(my_path[:-1])

In [2]:
RB = pd.read_csv(my_path_py+'\\1_RawBased\\SilScoreRB_2015to2020.csv', sep=',')
FB = pd.read_csv(my_path_py+'\\2_FeatureBased\\Resultados_Scores\\SilScore_18FB.csv', sep=',')
FB = FB.drop('Unnamed: 0', axis=1)
FB

,EUCLIDEAN-HAC,CORRELATION-HAC,SPEARMAN-HAC,DTW-HAC,EUCLIDEAN-KM,CORRELATION-KM,SPEARMAN-KM,DTW-KM,EUCLIDEAN-DB,CORRELATION-DB,SPEARMAN-DB,DTW-DB
0,0.974306,0.776843,0.375904,0.974289,0.97558,0.781621,0.399945,0.975568,0.586864,0.517453,0.438144,0.575432

In [3]:
compara = pd.DataFrame()
compara['Metrica'] = RB['Metrica']
compara['HAC RB'] = RB['SIL HAC RB']
compara['HAC FB'] = [FB['EUCLIDEAN-HAC'][0], FB['CORRELATION-HAC'][0], FB['SPEARMAN-HAC'][0], FB['DTW-HAC'][0]]
compara['KM RB'] = RB['SIL KM RB']
compara['KM FB'] = [FB['EUCLIDEAN-KM'][0], FB['CORRELATION-KM'][0], FB['SPEARMAN-KM'][0], FB['DTW-KM'][0]]
compara['DBSCAN RB'] = RB['SIL DB RB']
compara['DBSCAN FB'] = [FB['EUCLIDEAN-DB'][0], FB['CORRELATION-DB'][0], FB['SPEARMAN-DB'][0], FB['DTW-DB'][0]]

compara

     Metrica    HAC RB    HAC FB     KM RB     KM FB  DBSCAN RB  DBSCAN FB
0  Euclidean  0.755502  0.974306  0.758430  0.975580   0.436324   0.586864
1    Pearson  0.619035  0.776843  0.645673  0.781621   0.575971   0.517453
2   Spearman  0.612658  0.375904  0.641589  0.399945   0.501246   0.438144
3        DTW  0.655585  0.974289  0.681916  0.975568   0.273476   0.575432

In [4]:
FB_C = pd.read_csv(my_path_py+'\\2_FeatureBased\\Resultados_Scores\\CHZScore_18FB.csv', sep=',')
FB_C = FB_C.drop('Unnamed: 0', axis=1)

compara2 = pd.DataFrame()
compara2['Metrica'] = RB['Metrica']
compara2['HAC RB'] = RB['CHZ HAC RB']
compara2['HAC FB'] = [FB_C['EUCLIDEAN-HAC'][0], FB_C['CORRELATION-HAC'][0], FB_C['SPEARMAN-HAC'][0], FB_C['DTW-HAC'][0]]
compara2['KM RB'] = RB['CHZ KM RB']
compara2['KM FB'] = [FB_C['EUCLIDEAN-KM'][0], FB_C['CORRELATION-KM'][0], FB_C['SPEARMAN-KM'][0], FB_C['DTW-KM'][0]]
compara2['DBSCAN RB'] = RB['CHZ DB RB']
compara2['DBSCAN FB'] = [FB_C['EUCLIDEAN-DB'][0], FB_C['CORRELATION-DB'][0], FB_C['SPEARMAN-DB'][0], FB_C['DTW-DB'][0]]

compara2

,Metrica,HAC RB,HAC FB,KM RB,KM FB,DBSCAN RB,DBSCAN FB
0,Euclidean,2149.252996,271902.776957,2302.833110,280626.618215,76.750012,2.170604
1,Pearson,619.183951,2902.747554,680.461644,3269.282749,211.110326,83.268301
2,Spearman,525.505712,397.493129,629.396687,435.802347,116.545615,114.411452
3,DTW,1026.858890,271848.430052,1178.573502,280645.014647,53.835440,2.489706

In [5]:
FB_D = pd.read_csv(my_path_py+'\\2_FeatureBased\\Resultados_Scores\\DAVIES_18FB.csv', sep=',')
FB_D = FB_D.drop('Unnamed: 0', axis=1)

compara3 = pd.DataFrame()
compara3['Metrica'] = RB['Metrica']
compara3['HAC RB'] = RB['DAVIES HAC RB']
compara3['HAC FB'] = [FB_D['EUCLIDEAN-HAC'][0], FB_D['CORRELATION-HAC'][0], FB_D['SPEARMAN-HAC'][0], FB_D['DTW-HAC'][0]]
compara3['KM RB'] = RB['DAVIES KM RB']
compara3['KM FB'] = [FB_D['EUCLIDEAN-KM'][0], FB_D['CORRELATION-KM'][0], FB_D['SPEARMAN-KM'][0], FB_D['DTW-KM'][0]]
compara3['DBSCAN RB'] = RB['DAVIES DB RB']
compara3['DBSCAN FB'] = [FB_D['EUCLIDEAN-DB'][0], FB_D['CORRELATION-DB'][0], FB_D['SPEARMAN-DB'][0], FB_D['DTW-DB'][0]]

compara3

     Metrica    HAC RB    HAC FB     KM RB     KM FB  DBSCAN RB  DBSCAN FB
0  Euclidean  0.577075  0.219227  0.572247  0.268636   0.917916   1.689526
1    Pearson  0.841797  0.523132  0.825956  0.581165   1.184973   1.382753
2   Spearman  1.070690  0.917704  0.918351  0.904328   1.121669   1.204489
3        DTW  0.828137  0.219237  0.809867  0.268611   1.107366   1.692070